<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_sign_in</name>
   <tag></tag>
   <elementGuidId>11c6c48f-2010-4ac3-916a-85a644d16492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Sign in&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b392a09-b620-4358-85bc-d04e22f9ebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-semibold text-gray-400 hover:text-gray-900 transition-colors</value>
      <webElementGuid>2d5398da-f6a8-4632-8238-1a2e63f74c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>60d8b84d-9193-4376-9a30-e5d91100f9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>47ca4edf-999e-4061-bcf8-f5e91d3d8a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3b975af8f8441b098bdfe13841faf220</value>
      <webElementGuid>7b67d7e7-fdb3-4239-b86a-a3274c805745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/login']</value>
      <webElementGuid>c7955df5-34eb-423c-9a0b-87e73259ca17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/login']</value>
      <webElementGuid>cdaeadbd-9c1f-46ed-955f-61100f91ebfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>5a2ee47a-78a8-4136-84d8-35907c37a75c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
