<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cart</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>56084399-bf48-43ba-b9dc-2ed0d71974f8</testSuiteGuid>
   <testCaseLink>
      <guid>678cb86c-b89f-482a-8e77-fb19d47ccea0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Verification/add product to cart with out login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e29858c-3fce-4c54-a076-03828cb263f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df0c7c95-d1dc-4004-9769-4762aed148d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Verification/Refresh page in cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e49e470-d741-4371-a0d5-883760cb3916</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05c809c7-90cf-4b58-b6e1-532ca19aa056</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1432e80f-2124-46ed-b409-91df357d481e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf36e567-e8b0-4ffd-8830-6b0787f67762</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Verification/Update quantity in cart page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac98463d-e02e-48a3-ae81-1cbcc4dc55a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b135bee-7b0b-4558-88c2-f06bffce8c98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6681932-0209-4b1c-b543-5fccd32782ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34c07ceb-ea56-4dcc-afe1-ce98169197e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Verification/Add Product to Test Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c893b8c1-3483-4a26-b391-8bf311d5aac4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Verification/Add product to cart with selection and custom quantity</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793579ad-cd9b-4ac0-864e-208055c421ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d1c173-2770-4f79-9b39-402d0d294191</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27c6ff3e-46e5-4273-bd94-960bba599f6e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>920aa5f0-a9a4-43dc-9d9e-abf19efe8d40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Verification/Add product to cart with login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83b957c7-7be8-4882-9d31-796a13f69c88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0426a70a-e31d-41e3-a63a-1d5a0afd043e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a652d27a-6973-4701-9d1f-578cb0133607</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e609889-f8ff-4283-b341-98d901cf5153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Verification/Remove item from cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a63cb84-bff7-4919-9541-cc9ff945f60d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27a92690-82d9-46c0-bfee-2afd1a2b8d8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e56d5f1e-d64a-4b10-8ee6-02731ae4a293</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
