<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Checkout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>799c1cf8-f3ab-4dd2-9686-31e522e2e828</testSuiteGuid>
   <testCaseLink>
      <guid>60e96582-a232-4810-b0cf-abb65309528e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Checkout and Payment Verification/Checkout item with new user login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>012974da-6b9c-4111-b09e-bc02cfee8404</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Checkout and Payment Verification/Checkout items and pay from VA order details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ca8284e-3657-417f-a895-eedbe6121e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c016d282-95f7-4347-8189-67fba3a2737d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd66a489-56ea-4d8b-915a-ab8f79e63dca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efaf33a2-9a0a-4458-bb5f-4601b974b229</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Checkout and Payment Verification/Checkout item without login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e140d2a7-8d94-459d-8913-8dd6cca85603</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3153e05b-59d0-4864-9d17-74238e50e870</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Checkout and Payment Verification/Checkout items without paying</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2526cd1-f430-4b95-9199-8815943a1bbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb034e9b-a8cc-4c33-9392-bb30f5735776</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05622cb2-7fd9-4d18-84b9-4145c7177144</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20802e7e-7e34-4b2a-8afc-c96e4ce1191e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Checkout and Payment Verification/Checkout item with valid conditional</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1051f182-5ae7-4e7a-9d49-291485496703</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90a7248b-76d3-447f-bea0-c2f9584885cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac18320-ad86-4388-bb59-42b813a8fcf3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
