<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c2580082-9bf3-4fa7-a345-5ac6e0af0379</testSuiteGuid>
   <testCaseLink>
      <guid>6b883cf4-fa2e-49d2-bc5d-24090310690a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Verification/Login with valid credentials</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0ff45b1b-f44d-48fb-bc77-6e77858e1a3f</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/login-data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0ff45b1b-f44d-48fb-bc77-6e77858e1a3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>0e67afb4-20d2-4afa-ba17-0929b3379c0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0ff45b1b-f44d-48fb-bc77-6e77858e1a3f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>46fec9a9-a369-4d3b-8c1d-ee3f2cc4ee97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>236c6c59-85d9-4408-90cc-b22c9ab7bf18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75c3b447-82c0-4c37-8cc9-b94c1c731733</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Verification/Login with invalid credentials</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9cc8b166-ff9a-4f0c-bda0-93c4d5c23086</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/login-data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9cc8b166-ff9a-4f0c-bda0-93c4d5c23086</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>d191eabf-e9d1-46be-9e28-d22fbb9047ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9cc8b166-ff9a-4f0c-bda0-93c4d5c23086</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>360a11b7-735f-4ae1-8d4f-a37805c35287</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99e1dcac-389f-4b47-90ee-2e85f31907ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Verification/Login with empty input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>11d9ef75-3f90-4ced-a96c-5bdbe24bfcce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Verification/Login with unregistered email</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4db22d31-8dff-489b-86c9-6530f68acdd2</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>3-3</value>
         </iterationEntity>
         <testDataId>Data Files/login-data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4db22d31-8dff-489b-86c9-6530f68acdd2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>c7e99973-a363-4e9c-aa8f-c8373bf01cf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4db22d31-8dff-489b-86c9-6530f68acdd2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>c3f223d3-8d55-44c4-b7fa-aab4c724dd9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c19d315a-1bb6-44a3-aa26-b6dff19bc3ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>6097632a-c84b-4222-8197-92d6380d202b</id>
         <masked>false</masked>
         <name>password</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Login Verification/Login with SQL-Injection</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f5b2f136-2f54-466b-99e0-487238979cbc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login-sql-injection-data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f5b2f136-2f54-466b-99e0-487238979cbc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>27411304-d7af-438c-9fe6-3349d1fad114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f5b2f136-2f54-466b-99e0-487238979cbc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>6097632a-c84b-4222-8197-92d6380d202b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26df8895-8059-4b5a-80ee-77e2e3fa7bd6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
