<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_checkout</name>
   <tag></tag>
   <elementGuidId>539f6c6f-384e-4739-88d2-2aa8f018f684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Checkout')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;cart-checkout-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9eb3802-46fa-423b-9fe0-cda67d852f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cart-checkout-button</value>
      <webElementGuid>479f2354-0e6d-40c0-aac0-aa7db8d8c4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block text-center py-3.5 bg-[#111] text-white text-[13px] font-medium rounded-full hover:bg-[#333] transition-colors</value>
      <webElementGuid>9b413efd-7ccc-4ccb-882b-615e8b5c70fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/checkout</value>
      <webElementGuid>cbeec159-101f-44a7-88f4-d4fc502ebccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>223e53bc-4723-47aa-a041-ffc027c47944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable h-full antialiased&quot;]/body[@class=&quot;min-h-full flex flex-col bg-white text-[#1a1a1a] font-sans&quot;]/main[@class=&quot;flex-1&quot;]/div[@class=&quot;max-w-4xl mx-auto px-6 py-10&quot;]/div[@class=&quot;flex flex-col lg:flex-row gap-12&quot;]/div[@class=&quot;w-full lg:w-72&quot;]/div[@class=&quot;rounded-2xl bg-[#f7f7f7] p-6&quot;]/a[@class=&quot;block text-center py-3.5 bg-[#111] text-white text-[13px] font-medium rounded-full hover:bg-[#333] transition-colors&quot;]</value>
      <webElementGuid>48708f56-cf87-424a-adf7-18cdf0d1a498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Checkout')]</value>
      <webElementGuid>0635c813-d0a2-484f-bc13-67578fd07957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[1]</value>
      <webElementGuid>f74ab1bc-055f-42d8-9ae5-62c59ede1858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QWERTY'])[2]/preceding::a[1]</value>
      <webElementGuid>8aecf408-e6c0-4e3c-8ed7-f49a22cfbe91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[2]/preceding::a[1]</value>
      <webElementGuid>a9f399f5-9506-424b-b3f0-dd41cf895503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkout']/parent::*</value>
      <webElementGuid>137c617d-e9be-4c69-b448-858c3b9b8f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/checkout')]</value>
      <webElementGuid>c910ebd8-a202-42cb-8ccb-afbfdce76b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>48c0f576-3031-4ec5-85b5-3f1a1e2f8db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@data-testid = 'cart-checkout-button' and @href = '/checkout' and (text() = 'Checkout' or . = 'Checkout')]</value>
      <webElementGuid>2354f5df-1719-42b0-9c24-46ee11a5e74c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
