<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first_item_on_my_order_page</name>
   <tag></tag>
   <elementGuidId>dc49104c-6a95-4f46-bc3b-b27069d5f651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@data-testid='order-item'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;order-item-ORD-1778286670380-891e&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07af1c3f-3fe4-4acb-8b94-21bc3c355e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>order-item-ORD-1778286670380-891e</value>
      <webElementGuid>aed6d5c0-fdc8-4f84-b19c-4819954db585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block rounded-2xl bg-[#f7f7f7] p-5 hover:bg-[#f0f0f0] transition-colors</value>
      <webElementGuid>6b0471e7-c2ff-4995-a085-3c64c5f0ef34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/orders/ORD-1778286670380-891e</value>
      <webElementGuid>fe644c73-5cdf-4825-a7a0-1080ff9f3f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORD-1778286670380-891e9 Mei 2026pending1 itemRp 350.000</value>
      <webElementGuid>d96cbea7-bca9-4fe7-bfe7-7af89b4c1a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable h-full antialiased&quot;]/body[@class=&quot;min-h-full flex flex-col bg-white text-[#1a1a1a] font-sans&quot;]/main[@class=&quot;flex-1&quot;]/div[@class=&quot;max-w-3xl mx-auto px-6 py-10&quot;]/div[@class=&quot;space-y-3&quot;]/a[@class=&quot;block rounded-2xl bg-[#f7f7f7] p-5 hover:bg-[#f0f0f0] transition-colors&quot;]</value>
      <webElementGuid>3919bca6-04d6-430a-a93e-fc1fce3b661d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Orders'])[1]/following::a[1]</value>
      <webElementGuid>0f616864-b1f4-499c-b7a3-166a8888c122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UT'])[1]/following::a[2]</value>
      <webElementGuid>96b14e14-7171-4047-bd79-56991784eafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pending'])[2]/preceding::a[1]</value>
      <webElementGuid>c3975bcd-5f26-442d-8aab-dd31d0e8c9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/orders/ORD-1778286670380-891e')]</value>
      <webElementGuid>cc9b7001-16bd-4769-bee3-a71e53b7de7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/a</value>
      <webElementGuid>16033424-6f81-4f7f-aec1-cf44a2f784fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//*[@data-testid='order-item'])[1]</value>
      <webElementGuid>2ae42a3f-0e0b-415b-a433-a1314a669801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
