<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_va_code_on_order_details</name>
   <tag></tag>
   <elementGuidId>6dcbdade-2e17-4662-9505-57dc89bb64f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='order-va-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order-va-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;order-va-number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca85e33f-7936-4562-8034-c560064bce44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order-va-number</value>
      <webElementGuid>399083b0-52cd-4dcd-b6d2-ec415455fdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-mono font-black text-lg tracking-tight text-gray-900</value>
      <webElementGuid>979b0369-31f8-4904-89db-1572d183aac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>order-va-number</value>
      <webElementGuid>da7ca89c-bb94-4da1-bb6b-45335d95a164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>807728628890</value>
      <webElementGuid>153b6d98-7489-4726-8ce8-9574b4eb4754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-va-number&quot;)</value>
      <webElementGuid>050db500-0fd2-431e-abee-bcde6b5d9e98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='order-va-number']</value>
      <webElementGuid>26c0457f-c644-418e-8e5d-6c9f1c9d0a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bca va'])[1]/following::span[1]</value>
      <webElementGuid>9bc99a0a-e6ee-46df-9c5f-c667ea2defc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting Payment'])[1]/following::span[2]</value>
      <webElementGuid>9b4866b3-2724-437d-a764-4fcf50e15646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Simulator'])[1]/preceding::span[1]</value>
      <webElementGuid>8e9139be-5663-4cbb-b32a-4a0e6240842d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='807728628890']/parent::*</value>
      <webElementGuid>53cba6f2-9594-4907-8fe4-481896e459d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>d8f056a3-577e-4050-80b0-016804ea0b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'order-va-number' and @data-testid = 'order-va-number']</value>
      <webElementGuid>fb9742ae-a997-483b-91ce-e58efc11e68a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
