<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_va_code</name>
   <tag></tag>
   <elementGuidId>d57a871b-9519-4448-bc64-95db2552372f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='simulator-va-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#simulator-va-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;simulator-va-number&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f466efd0-2671-4995-a092-772dc0ea1e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simulator-va-number</value>
      <webElementGuid>d1ad8e6e-91f1-4821-90f1-984f468ff29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-3xl font-black text-gray-900 font-mono tracking-tight</value>
      <webElementGuid>766d2223-346d-4e1b-847a-e6dd07485a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>simulator-va-number</value>
      <webElementGuid>e29c1546-fe5a-4250-b4e7-ed005e974eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>807799023693</value>
      <webElementGuid>fc5f41f4-4b54-45cf-bb56-801039550365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simulator-va-number&quot;)</value>
      <webElementGuid>7e92ab4b-3dd3-418b-82c8-5ce0791e865f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='simulator-va-number']</value>
      <webElementGuid>65af5cad-3434-497b-8382-25819f179b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QWERTY Store'])[1]/following::p[5]</value>
      <webElementGuid>861dc188-ffa8-431b-867f-89224755336d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UT'])[1]/following::p[5]</value>
      <webElementGuid>25274e34-cf08-4fc6-9701-27a265b2e7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Code'])[1]/preceding::p[1]</value>
      <webElementGuid>1d888198-2c2a-41f4-a031-f4cd1a620cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close and wait for confirmation'])[1]/preceding::p[3]</value>
      <webElementGuid>479e5253-b596-4222-9003-734e41c83656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='807799023693']/parent::*</value>
      <webElementGuid>3e33e1f3-4cd6-4ad2-bd3a-f150529e434d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/p</value>
      <webElementGuid>49650eed-689d-433d-b483-40b67d2cb89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'simulator-va-number' and @data-testid = 'simulator-va-number']</value>
      <webElementGuid>84ae130a-0dfa-45c9-88e6-9575467917ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
