<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp_code_field</name>
   <tag></tag>
   <elementGuidId>652204d0-b664-4dbc-8527-20b232dfb208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;reset-password-otp-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79e95ab2-8bbf-4989-9d38-7bd6767043c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>reset-password-otp-input</value>
      <webElementGuid>074db993-72de-4479-a016-b447e5e4e81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter 6-digit code</value>
      <webElementGuid>fc1143e4-ba49-476c-b9a5-9bac4b987455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full pl-11 pr-4 py-3 bg-gray-50 border border-transparent rounded-2xl text-[14px] text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-gray-200 transition-all font-mono tracking-widest</value>
      <webElementGuid>09e1799a-d9b1-42f2-a25d-0c1076c17979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>1d12e32f-05d6-4966-ab2c-b9d4f46a0589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85145a4c-3af1-4946-a94c-9df3ebbf9ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable h-full antialiased&quot;]/body[@class=&quot;min-h-full flex flex-col bg-white text-[#1a1a1a] font-sans&quot;]/main[@class=&quot;flex-1&quot;]/div[@class=&quot;min-h-[80vh] flex items-center justify-center px-4 py-12&quot;]/div[@class=&quot;w-full max-w-md&quot;]/div[1]/form[@class=&quot;space-y-4&quot;]/div[1]/div[@class=&quot;relative&quot;]/input[@class=&quot;w-full pl-11 pr-4 py-3 bg-gray-50 border border-transparent rounded-2xl text-[14px] text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-gray-200 transition-all font-mono tracking-widest&quot;]</value>
      <webElementGuid>f1d3337f-69b4-4dd0-ab9f-0af3c8f2e779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>a5c0fe69-946a-4d8d-96f5-5ccbdebea070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f8bff639-0f20-4a05-bf29-c14ad919b102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@data-testid = 'reset-password-otp-input' and @placeholder = 'Enter 6-digit code' and @type = 'text']</value>
      <webElementGuid>2381fdc1-a204-480f-bf8d-e5e6fc44c4a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
