<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_otp_code</name>
   <tag></tag>
   <elementGuidId>61609b54-ab2a-42b1-b6bd-f6c2948514b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@data-testid='otp-code'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp-code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;otp-code&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e561fcff-2c58-456a-811d-b02b77cb2ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp-code</value>
      <webElementGuid>248fccae-8d04-446e-8ae8-7e387f1ffe3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>otp-code</value>
      <webElementGuid>fc739d91-8650-448d-885b-a67a14204b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-bold text-gray-900 bg-gray-100 px-1.5 py-0.5 rounded border border-gray-200</value>
      <webElementGuid>7c7039ea-7879-49ef-b63d-ed7c467a1979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>233978</value>
      <webElementGuid>deec535b-f586-4979-a18d-c62954cea1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp-code&quot;)</value>
      <webElementGuid>001f0de8-2d9e-4bfb-bd48-6313ec887c06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='otp-code']</value>
      <webElementGuid>a004659d-9066-4501-9b77-46c4b334f15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QWERTY - Password Reset OTP'])[1]/following::span[1]</value>
      <webElementGuid>ddd87a88-860a-4bb9-b2ce-1e1cc39a73ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::span[1]</value>
      <webElementGuid>0147561b-6ea8-43d3-bfdf-4a784707874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivered via QWERTY SMTP Simulation'])[1]/preceding::span[1]</value>
      <webElementGuid>634b0b30-63b3-4c57-888b-5739a1db1d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QWERTY'])[2]/preceding::span[2]</value>
      <webElementGuid>fa9ab634-9149-4707-bee2-aaed04202635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='233978']/parent::*</value>
      <webElementGuid>aaa8a999-ef36-4d56-bb2b-be161d23b05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span</value>
      <webElementGuid>91a59806-35e1-4b45-ac8b-f5c888e00051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//*[@data-testid='otp-code'])[1]</value>
      <webElementGuid>cd57eb63-0ff8-4984-b9e5-33f9f5fd939a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
