<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_field</name>
   <tag></tag>
   <elementGuidId>3533d4de-c9e1-4cc9-99eb-2e08baaf5efb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'login-email-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;login-email-input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;login-email-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c0b9614-dc9d-4ab4-9078-254f4ac76618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login-email-input</value>
      <webElementGuid>ba515c2e-4716-4688-b92e-2316f8727b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>you@example.com</value>
      <webElementGuid>2326bf1e-946a-4e57-adb4-6d571852574a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:border-gray-400 focus:bg-white transition-all</value>
      <webElementGuid>cd2b3d53-5286-463d-aa48-c6f4291277b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ce76084e-1c3d-4ec5-a77b-8a06cbc8a093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a595885aa88e049edf57a02c8d30c2c7</value>
      <webElementGuid>f7e7b68c-2234-4949-8505-08c98e6542d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'login-email-input']</value>
      <webElementGuid>546712d4-f278-43bd-8d0d-25204f7da376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'login-email-input']</value>
      <webElementGuid>4cbbad37-98d2-49ca-80f0-f76ccf4ac8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@data-testid = 'login-email-input' and @placeholder = 'you@example.com' and @type = 'email']</value>
      <webElementGuid>42df115e-606e-4dfd-b07a-a4867d1f6059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
