<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_invalid-email-or-password</name>
   <tag></tag>
   <elementGuidId>6da71225-e179-49c9-9bf3-1092c52d09a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'login-error-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;login-error-message&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;login-error-message&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>181d6e1b-d3c0-4a6a-82de-7b9e294c5017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login-error-message</value>
      <webElementGuid>0b9c7191-3c38-4618-b5f7-2147f4415f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-5 p-3 bg-red-50 text-red-600 text-[13px] rounded-xl text-center font-medium</value>
      <webElementGuid>f727d722-2aac-42d0-85b3-0b0935497e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid email or password</value>
      <webElementGuid>89be52eb-20a0-485f-86b1-e47cc512e4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-418d4e6f9ea3454be275d80bc0306baa</value>
      <webElementGuid>0c3721ea-170d-4b4e-ab0c-406cb02667cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'login-error-message']</value>
      <webElementGuid>a28deaf6-c1b7-4163-a00c-4b7c96827c1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'login-error-message']</value>
      <webElementGuid>cd7cfcef-896d-44e1-86f4-4f59d4c0fec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-testid = 'login-error-message' and (text() = 'Invalid email or password' or . = 'Invalid email or password')]</value>
      <webElementGuid>389698c0-f4d1-4d88-9bbd-96af24e0be60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
