<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_invalid-email-or-password</name>
   <tag></tag>
   <elementGuidId>d440ae90-2ddc-4774-a573-5bafea0d816c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid = 'login-error-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid=&quot;login-error-message&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;login-error-message&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7af23758-5710-4fe7-a75d-d57c909130fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login-error-message</value>
      <webElementGuid>acd06a40-a295-4958-8f3e-fcd8169f19b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-5 p-3 bg-red-50 text-red-600 text-[13px] rounded-xl text-center font-medium</value>
      <webElementGuid>1f890a6c-78cb-4348-9e1b-78f507f7c4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid email or password</value>
      <webElementGuid>78a6b225-1244-44b1-8735-0a7671438444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-418d4e6f9ea3454be275d80bc0306baa</value>
      <webElementGuid>abb4a965-c825-463a-b933-92b0302f9d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-testid = 'login-error-message']</value>
      <webElementGuid>98f53c24-e95a-43fc-ad7a-a7808ae0bc02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-testid = 'login-error-message']</value>
      <webElementGuid>ceda1b20-4d33-4f93-9a22-5de39456cccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-testid = 'login-error-message' and (text() = 'Invalid email or password' or . = 'Invalid email or password')]</value>
      <webElementGuid>39d6aed6-557b-4681-8c4f-56e39d705482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
